spring:
  #security:
   # oauth2:
    #  resourceserver:
     #   jwt:
      #    issuer-uri: http://localhost:8080/realms/master
       #   jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/auth

  datasource:
    url: jdbc:mysql://localhost:3306/partite
    username: 'root'
    password: '_D4t4b4s3_'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8081